- unlabelled: [0, 0, 0]
- road: [0, 0, 1]
- vegetation: [0, 1, 0]
- building: [1, 0, 0]
- grass: [0, 0.4, 0]
- vehicle: [0, 1, 1]
- human: [1, 0, 1]
- gravel: [0, 0.5, 0.5]
- tree_trunk: [0.5, 0.2, 0.2]
- light_pole: [1, 0.5, 0]
