- unlabelled: [0, 0, 0]
- road: [0, 0, 1]
- chair: [0, 1, 0]
- building: [1, 0, 0]
- boxes: [0, 0.4, 0]
- vehicle: [0, 1, 1]
- cones: [1, 0, 1]
- big_bench: [0, 0.5, 0.5]
- tree_trunk: [0.5, 0.2, 0.2]
